# Generated by Django 4.2.3 on 2023-07-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='start_working_at',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
    ]
