# Generated by Django 4.2.3 on 2023-07-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_rename_active_worker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='employers.department'),
        ),
    ]
