# Generated by Django 4.2.3 on 2023-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_remove_department_chief_alter_department_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='inner_phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Внутренний номер'),
        ),
    ]
