# Generated by Django 4.2.3 on 2023-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_filial_alter_worker_department_alter_worker_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='has_access_to_wb_bot',
            field=models.BooleanField(default=False, verbose_name='Имеет доступ к боту Wildberries'),
        ),
    ]
