# Generated by Django 4.2.3 on 2023-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_worker_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='icq',
            field=models.CharField(blank=True, max_length=64, verbose_name='ICQ'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tg_id',
            field=models.BigIntegerField(blank=True, help_text='Свой id в телеграмме можно узнать написав боту @userinfobot', null=True, verbose_name='ID в телеграмме'),
        ),
    ]
