# Generated by Django 4.2.3 on 2023-08-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wb.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_code_number',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='номер QR-кода'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING', 'В работе'), ('SORTED', 'Отсортировано'), ('SOLD', 'Получено покупателем'), ('CANCELED', 'Отменена'), ('CANCELED_BY_CLIENT', 'Отмена покупателем'), ('DEFECT', 'Брак'), ('READY_FOR_PICK_UP', 'Прибыло на ПВЗ')], default='WAITING', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=128, verbose_name='Штрихкод'),
        ),
    ]
