# Generated by Django 4.2.3 on 2023-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0003_alter_order_product_alter_order_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=255, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
