# Generated by Django 4.2.3 on 2023-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=32, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=32, verbose_name='Бренд'),
        ),
    ]
