# Generated by Django 4.2.3 on 2023-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_alter_product_barcode_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['article'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(verbose_name='Создана'),
        ),
    ]
