# Generated by Django 4.2.3 on 2023-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='is_done',
        ),
        migrations.AddField(
            model_name='supply',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Открыта'),
        ),
    ]
