# Generated by Django 4.2.3 on 2023-08-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_remove_supply_is_done_supply_is_open'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
